name: CI/CD - SvelteKit with Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18  
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install  
      - name: Build the app
        run: npm run build  

      - name: Run tests
        run: npm test  # Replace with your test command